# Generated by Django 2.2.28 on 2023-03-27 04:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('pkBodega', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=128)),
                ('ciudad', models.CharField(choices=[('MED', 'Medellín'), ('CALI', 'Cali'), ('CART', 'Cartagena'), ('SOL', 'Soledad'), ('B/Q', 'Barranquilla'), ('SOAC', 'Soacha'), ('BCM', 'Bucaramanga'), ('CUC', 'Cucuta'), ('BOG', 'Bogotá'), ('IBG', 'Ibague')], default='CALI', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('pkCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=256, unique=True)),
                ('rutaImagen', models.ImageField(upload_to='../media/categoriasImagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('pknit', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe tener formato: '+7777777'. Up to 10 digits allowed.", regex='^\\+?1?\\d{7,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('pkSubCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSubCategoria', models.CharField(max_length=256, unique=True)),
                ('fkCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('pkProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='null', max_length=300)),
                ('descripcion', models.CharField(max_length=1024)),
                ('iva', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('precio', models.IntegerField()),
                ('rutaImagen', models.ImageField(upload_to='../media/productosImagenes')),
                ('fkSubCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.SubCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesProducto',
            fields=[
                ('pkDetallesP', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(choices=[('L', 'l'), ('M', 'm'), ('S', 's'), ('XL', 'xl'), ('XS', 'xs')], max_length=32)),
                ('color', models.CharField(choices=[('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Blanco', 'Blanco'), ('Rosado', 'Rosado'), ('Otros', 'Otro'), ('Negro', ' Negro'), ('Verde', 'Verde'), ('Marron', 'Marrón'), ('Naranja', 'Naranja'), ('Rojo', 'Rojo'), ('Gris', 'Gris'), ('Morado', 'Morado'), ('Beige', 'Beige')], max_length=64)),
                ('cantidad', models.IntegerField()),
                ('fkBodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Bodega')),
                ('fkProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Producto')),
                ('nit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Proveedor')),
            ],
        ),
    ]
