# Generated by Django 2.2.28 on 2023-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('B/Q', 'Barranquilla'), ('IBG', 'Ibague'), ('BOG', 'Bogotá'), ('SOAC', 'Soacha'), ('MED', 'Medellín'), ('CUC', 'Cucuta'), ('BCM', 'Bucaramanga'), ('CART', 'Cartagena'), ('CALI', 'Cali'), ('SOL', 'Soledad')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Naranja', 'Naranja'), ('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Blanco', 'Blanco'), ('Otros', 'Otro'), ('Rosado', 'Rosado'), ('Verde', 'Verde'), ('Gris', 'Gris'), ('Beige', 'Beige'), ('Marron', 'Marrón'), ('Morado', 'Morado'), ('Negro', ' Negro'), ('Rojo', 'Rojo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('XS', 'xs'), ('M', 'm'), ('S', 's'), ('L', 'l'), ('XL', 'xl')], max_length=32),
        ),
    ]
