# Generated by Django 2.2.28 on 2023-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20230327_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOL', 'Soledad'), ('BOG', 'Bogotá'), ('MED', 'Medellín'), ('CUC', 'Cucuta'), ('BCM', 'Bucaramanga'), ('CART', 'Cartagena'), ('B/Q', 'Barranquilla'), ('SOAC', 'Soacha'), ('CALI', 'Cali'), ('IBG', 'Ibague')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Morado', 'Morado'), ('Rosado', 'Rosado'), ('Beige', 'Beige'), ('Gris', 'Gris'), ('Negro', ' Negro'), ('Verde', 'Verde'), ('Rojo', 'Rojo'), ('Naranja', 'Naranja'), ('Azul', 'Azul'), ('Blanco', 'Blanco'), ('Otros', 'Otro'), ('Amarillo', 'Amarillo'), ('Marron', 'Marrón')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('L', 'l'), ('S', 's'), ('XL', 'xl'), ('M', 'm'), ('XS', 'xs')], max_length=32),
        ),
    ]
