# Generated by Django 2.2.28 on 2023-03-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20230327_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('CALI', 'Cali'), ('CART', 'Cartagena'), ('SOAC', 'Soacha'), ('B/Q', 'Barranquilla'), ('MED', 'Medellín'), ('IBG', 'Ibague'), ('BOG', 'Bogotá'), ('BCM', 'Bucaramanga'), ('CUC', 'Cucuta'), ('SOL', 'Soledad')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Rosado', 'Rosado'), ('Beige', 'Beige'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Gris', 'Gris'), ('Azul', 'Azul'), ('Blanco', 'Blanco'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Marron', 'Marrón'), ('Negro', ' Negro'), ('Morado', 'Morado'), ('Otros', 'Otro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('M', 'm'), ('XS', 'xs'), ('L', 'l'), ('S', 's'), ('XL', 'xl')], max_length=32),
        ),
    ]
