# Generated by Django 2.2.28 on 2023-03-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20230327_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOAC', 'Soacha'), ('SOL', 'Soledad'), ('CART', 'Cartagena'), ('IBG', 'Ibague'), ('CUC', 'Cucuta'), ('BCM', 'Bucaramanga'), ('MED', 'Medellín'), ('B/Q', 'Barranquilla'), ('CALI', 'Cali'), ('BOG', 'Bogotá')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Amarillo', 'Amarillo'), ('Negro', ' Negro'), ('Azul', 'Azul'), ('Marron', 'Marrón'), ('Morado', 'Morado'), ('Blanco', 'Blanco'), ('Rosado', 'Rosado'), ('Naranja', 'Naranja'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Beige', 'Beige'), ('Otros', 'Otro'), ('Gris', 'Gris')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('XS', 'xs'), ('L', 'l'), ('XL', 'xl'), ('M', 'm'), ('S', 's')], max_length=32),
        ),
    ]
