# Generated by Django 2.2.28 on 2023-03-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20230327_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('CALI', 'Cali'), ('CART', 'Cartagena'), ('BCM', 'Bucaramanga'), ('IBG', 'Ibague'), ('SOAC', 'Soacha'), ('MED', 'Medellín'), ('SOL', 'Soledad'), ('B/Q', 'Barranquilla'), ('CUC', 'Cucuta'), ('BOG', 'Bogotá')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Verde', 'Verde'), ('Morado', 'Morado'), ('Gris', 'Gris'), ('Otros', 'Otro'), ('Rosado', 'Rosado'), ('Marron', 'Marrón'), ('Naranja', 'Naranja'), ('Rojo', 'Rojo'), ('Blanco', 'Blanco'), ('Amarillo', 'Amarillo'), ('Azul', 'Azul'), ('Negro', ' Negro'), ('Beige', 'Beige')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('S', 's'), ('XS', 'xs'), ('L', 'l'), ('M', 'm'), ('XL', 'xl')], max_length=32),
        ),
    ]
