# Generated by Django 2.2.28 on 2023-03-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20230327_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('CART', 'Cartagena'), ('BOG', 'Bogotá'), ('BCM', 'Bucaramanga'), ('SOL', 'Soledad'), ('SOAC', 'Soacha'), ('IBG', 'Ibague'), ('CALI', 'Cali'), ('MED', 'Medellín'), ('B/Q', 'Barranquilla'), ('CUC', 'Cucuta')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Marron', 'Marrón'), ('Rosado', 'Rosado'), ('Blanco', 'Blanco'), ('Negro', ' Negro'), ('Naranja', 'Naranja'), ('Morado', 'Morado'), ('Rojo', 'Rojo'), ('Beige', 'Beige'), ('Gris', 'Gris'), ('Otros', 'Otro'), ('Amarillo', 'Amarillo'), ('Verde', 'Verde')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl')], max_length=32),
        ),
    ]
