# Generated by Django 2.2.28 on 2023-03-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20230327_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('CART', 'Cartagena'), ('MED', 'Medellín'), ('IBG', 'Ibague'), ('BCM', 'Bucaramanga'), ('BOG', 'Bogotá'), ('CALI', 'Cali'), ('SOAC', 'Soacha'), ('B/Q', 'Barranquilla'), ('SOL', 'Soledad'), ('CUC', 'Cucuta')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Marron', 'Marrón'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Morado', 'Morado'), ('Blanco', 'Blanco'), ('Negro', ' Negro'), ('Rojo', 'Rojo'), ('Gris', 'Gris'), ('Beige', 'Beige'), ('Otros', 'Otro'), ('Rosado', 'Rosado'), ('Verde', 'Verde')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('L', 'l'), ('M', 'm'), ('S', 's'), ('XL', 'xl'), ('XS', 'xs')], max_length=32),
        ),
    ]
