# Generated by Django 2.2.28 on 2023-03-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20230327_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOL', 'Soledad'), ('BOG', 'Bogotá'), ('MED', 'Medellín'), ('CART', 'Cartagena'), ('IBG', 'Ibague'), ('CUC', 'Cucuta'), ('SOAC', 'Soacha'), ('CALI', 'Cali'), ('B/Q', 'Barranquilla'), ('BCM', 'Bucaramanga')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Gris', 'Gris'), ('Verde', 'Verde'), ('Blanco', 'Blanco'), ('Negro', ' Negro'), ('Beige', 'Beige'), ('Morado', 'Morado'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Rosado', 'Rosado'), ('Marron', 'Marrón'), ('Rojo', 'Rojo'), ('Otros', 'Otro'), ('Azul', 'Azul')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('XL', 'xl'), ('S', 's'), ('L', 'l'), ('XS', 'xs'), ('M', 'm')], max_length=32),
        ),
    ]
