# Generated by Django 2.2.28 on 2023-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20230327_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOL', 'Soledad'), ('CALI', 'Cali'), ('CUC', 'Cucuta'), ('CART', 'Cartagena'), ('IBG', 'Ibague'), ('BOG', 'Bogotá'), ('BCM', 'Bucaramanga'), ('MED', 'Medellín'), ('B/Q', 'Barranquilla'), ('SOAC', 'Soacha')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Verde', 'Verde'), ('Rosado', 'Rosado'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Morado', 'Morado'), ('Otros', 'Otro'), ('Gris', 'Gris'), ('Negro', ' Negro'), ('Blanco', 'Blanco'), ('Naranja', 'Naranja'), ('Azul', 'Azul'), ('Beige', 'Beige'), ('Marron', 'Marrón')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('M', 'm'), ('L', 'l'), ('S', 's'), ('XL', 'xl'), ('XS', 'xs')], max_length=32),
        ),
    ]
