# Generated by Django 2.2.28 on 2023-03-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20230327_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('CUC', 'Cucuta'), ('SOL', 'Soledad'), ('CART', 'Cartagena'), ('SOAC', 'Soacha'), ('B/Q', 'Barranquilla'), ('BCM', 'Bucaramanga'), ('MED', 'Medellín'), ('BOG', 'Bogotá'), ('IBG', 'Ibague'), ('CALI', 'Cali')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='color',
            field=models.CharField(choices=[('Rosado', 'Rosado'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Verde', 'Verde'), ('Otros', 'Otro'), ('Gris', 'Gris'), ('Beige', 'Beige'), ('Rojo', 'Rojo'), ('Marron', 'Marrón'), ('Negro', ' Negro'), ('Azul', 'Azul'), ('Blanco', 'Blanco'), ('Morado', 'Morado')], max_length=64),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='talla',
            field=models.CharField(choices=[('S', 's'), ('L', 'l'), ('XL', 'xl'), ('XS', 'xs'), ('M', 'm')], max_length=32),
        ),
    ]
