# Generated by Django 2.2.28 on 2023-03-27 04:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_auto_20230327_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorDuenio',
            fields=[
                ('pkAdministradorDuenio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=128, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('tipo', models.CharField(choices=[('CEO', 'Duenio'), ('ADMIN', 'Administrador')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=32)),
                ('telefono', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe tener formato: '+7777777'. Up to 10 digits allowed.", regex='^\\+?1?\\d{7,10}$')])),
                ('tipoDocumento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte'), ('CC', 'Cedula de Ciudadania')], max_length=3)),
                ('numeroDocumento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('pkCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioActual', models.FloatField()),
                ('fkDetalleProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.DetallesProducto')),
                ('fkNombreCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Cliente')),
            ],
        ),
    ]
