# Generated by Django 2.2.28 on 2023-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania')], max_length=3),
        ),
    ]
