# Generated by Django 2.2.28 on 2023-03-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20230327_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('PAS', 'Pasaporte'), ('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad')], max_length=3),
        ),
    ]
