# Generated by Django 2.2.28 on 2023-03-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20230327_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorduenio',
            name='tipo',
            field=models.CharField(choices=[('CEO', 'Duenio'), ('ADMIN', 'Administrador')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], max_length=3),
        ),
    ]
