# Generated by Django 2.2.28 on 2023-03-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20230327_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorduenio',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CEO', 'Duenio')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('PAS', 'Pasaporte'), ('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad')], max_length=3),
        ),
    ]
