# Generated by Django 2.2.28 on 2023-03-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20230327_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], max_length=3),
        ),
    ]
