# Generated by Django 2.2.28 on 2023-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20230327_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorduenio',
            name='tipo',
            field=models.CharField(choices=[('CEO', 'Duenio'), ('ADMIN', 'Administrador')], max_length=5),
        ),
    ]
