# Generated by Django 2.2.28 on 2023-03-27 04:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_auto_20230327_0402'),
        ('inventario', '0003_auto_20230327_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('pkFactura', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(choices=[('SOL', 'Soledad'), ('BOG', 'Bogotá'), ('MED', 'Medellín'), ('CUC', 'Cucuta'), ('BCM', 'Bucaramanga'), ('CART', 'Cartagena'), ('B/Q', 'Barranquilla'), ('SOAC', 'Soacha'), ('CALI', 'Cali'), ('IBG', 'Ibague')], default='CALI', max_length=4)),
                ('direccion', models.CharField(max_length=32)),
                ('fecha', models.DateField()),
                ('fkCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PagosDebito',
            fields=[
                ('pkPagosDebito', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjetaDebito', models.IntegerField()),
                ('ahorros', models.BooleanField()),
                ('porcentajePago', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='PagosCredito',
            fields=[
                ('pkPagosCredito', models.AutoField(primary_key=True, serialize=False)),
                ('numeroAprobacion', models.CharField(max_length=32)),
                ('cuotas', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('fechaAprobacion', models.DateField()),
                ('entidadAprobacion', models.CharField(choices=[('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD'), ('VI', 'VISA')], max_length=2)),
                ('porcentajePago', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fkDetallesP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.DetallesProducto')),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoSubCategoria',
            fields=[
                ('pkDescuentoSubCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateField()),
                ('porcentajeDescuento', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('fkSubCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.SubCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('pkDescuentoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateField()),
                ('porcentajeDescuento', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('fkProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoCategoria',
            fields=[
                ('pkDescuentoCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateField()),
                ('porcentajeDescuento', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('fkCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Categoria')),
            ],
        ),
    ]
