# Generated by Django 2.2.28 on 2023-03-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('SOL', 'Soledad'), ('MED', 'Medellín'), ('CUC', 'Cucuta'), ('BOG', 'Bogotá'), ('BCM', 'Bucaramanga'), ('IBG', 'Ibague'), ('CALI', 'Cali'), ('CART', 'Cartagena'), ('B/Q', 'Barranquilla'), ('SOAC', 'Soacha')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('CA', 'MASTERCARD'), ('AX', 'AMERICANEXPRESS'), ('VI', 'VISA')], max_length=2),
        ),
    ]
