# Generated by Django 2.2.28 on 2023-03-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20230327_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('CUC', 'Cucuta'), ('IBG', 'Ibague'), ('SOL', 'Soledad'), ('MED', 'Medellín'), ('BOG', 'Bogotá'), ('SOAC', 'Soacha'), ('B/Q', 'Barranquilla'), ('CART', 'Cartagena'), ('CALI', 'Cali'), ('BCM', 'Bucaramanga')], default='CALI', max_length=4),
        ),
    ]
