# Generated by Django 2.2.28 on 2023-03-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20230327_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('BCM', 'Bucaramanga'), ('SOL', 'Soledad'), ('CALI', 'Cali'), ('IBG', 'Ibague'), ('CUC', 'Cucuta'), ('MED', 'Medellín'), ('B/Q', 'Barranquilla'), ('BOG', 'Bogotá'), ('SOAC', 'Soacha'), ('CART', 'Cartagena')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('VI', 'VISA'), ('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD')], max_length=2),
        ),
    ]
