# Generated by Django 2.2.28 on 2023-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20230327_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('B/Q', 'Barranquilla'), ('IBG', 'Ibague'), ('BOG', 'Bogotá'), ('CALI', 'Cali'), ('BCM', 'Bucaramanga'), ('CART', 'Cartagena'), ('SOAC', 'Soacha'), ('MED', 'Medellín'), ('CUC', 'Cucuta'), ('SOL', 'Soledad')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('CA', 'MASTERCARD'), ('VI', 'VISA'), ('AX', 'AMERICANEXPRESS')], max_length=2),
        ),
    ]
