# Generated by Django 2.2.28 on 2023-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20230327_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('BOG', 'Bogotá'), ('MED', 'Medellín'), ('IBG', 'Ibague'), ('SOL', 'Soledad'), ('BCM', 'Bucaramanga'), ('CUC', 'Cucuta'), ('SOAC', 'Soacha'), ('B/Q', 'Barranquilla'), ('CART', 'Cartagena'), ('CALI', 'Cali')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('CA', 'MASTERCARD'), ('AX', 'AMERICANEXPRESS'), ('VI', 'VISA')], max_length=2),
        ),
    ]
