# Generated by Django 2.2.28 on 2023-03-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20230327_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('CALI', 'Cali'), ('B/Q', 'Barranquilla'), ('CUC', 'Cucuta'), ('BOG', 'Bogotá'), ('MED', 'Medellín'), ('IBG', 'Ibague'), ('CART', 'Cartagena'), ('SOAC', 'Soacha'), ('BCM', 'Bucaramanga'), ('SOL', 'Soledad')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('VI', 'VISA'), ('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD')], max_length=2),
        ),
    ]
