# Generated by Django 2.2.28 on 2023-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20230327_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(choices=[('BCM', 'Bucaramanga'), ('CUC', 'Cucuta'), ('B/Q', 'Barranquilla'), ('BOG', 'Bogotá'), ('SOAC', 'Soacha'), ('SOL', 'Soledad'), ('CALI', 'Cali'), ('CART', 'Cartagena'), ('MED', 'Medellín'), ('IBG', 'Ibague')], default='CALI', max_length=4),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD'), ('VI', 'VISA')], max_length=2),
        ),
    ]
